### ISSUE TITLE
Problema con las pets

### ISSUE THREAD

**Issue by alexandros007** [MajokGG/MagieNetwork#1]
**Describe el error**
Yo abrí una caja y me toco un caballo como pet, pero no me aparece ni en coleccionables

**Versión de tu MC**
1.16.5

**Versión del Servidor**
2.4833.07-sv

**Capturas (Medios)**

![Screenshot_1](https://user-images.githubusercontent.com/34277998/111918026-697bc500-8a83-11eb-8948-f73cbc9f367c.png)

**Comment by MilkkaCute** [comment]
Hola @alexandros007 ,
Realmente no se considera un error, ya que eso se arregla reconectándose al servidor.
